CREATE DATABASE DBA;

USE DBA;

CREATE TABLE Product_Category(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100),
description TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deleted_at TIMESTAMP
);

CREATE TABLE Product_Inventory(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
quantity INT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deleted_at TIMESTAMP
);

CREATE TABLE discount(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
description TEXT,
discount_percent DECIMAL NOT NULL,
active BOOLEAN,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deleted_at TIMESTAMP);

CREATE TABLE Product(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(45) NOT NULL,
description VARCHAR(255),
SKU VARCHAR(255),
category_id INT,
FOREIGN KEY(category_id) REFERENCES Product_Category(id)
ON DELETE CASCADE,
inventory_id INT NOT NULL,
FOREIGN KEY(inventory_id) REFERENCES Product_Inventory(id)
ON DELETE CASCADE,
price DECIMAL NOT NULL,
discount_id INT,
FOREIGN KEY(discount_id) REFERENCES discount(id)
ON DELETE CASCADE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deleted_at TIMESTAMP);

